language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: wvr4yAnIc2l6RNB/94tb3mZUWpeL55U2ayMNQf9dTvw6KW+b+CpQVHXvJgRbZZsw9bBNnUGCwjbjxBjuiELEdb7PSuMs3zIOAjXMOY9qjauYMwcc4DFB4mEV/QO2FBzsh4laQrkGdS9Y+pGx4aPETcNWxhB1hIUCQzjbZEUQLxrLkDIbBMGCTu6CqDy+AQM4ETXokUHHiG/qcGrsENJdyE8oaAVbkqro0qp6BrMxLiIZIQVn/VvInpuaVAUmiMQWI3Kk5aPDrpHeuPyUF/AzED6Q9ZlatYwguRyV43Z/deMMRdt2vm8R1NSGW9rDhOmyPqPFdVcCnmSj8yi182oMU/JnVFPZEIMSwrDL4OhYK8Ac+S8GfVnB/2j4P+kajXUgPEQxBzND4IYR8hoIBuEgTC+QkLo4Hp1E/DlPBwuxrbfYxEdWHM3gTtqMmdoRdAVmuuMqf8PMsx0RNeucLxRjk7Fep1mF7jQ9+eCE2BOyZ8XQ/nLDQODitfTwQ21Ly+H5ieT/pRUdFvkqeEEjbKpcwaxfj4mW4AiJTxZW9zXHi6l5bzhQHtx0wnhHvMQ8Xt85GDFr8oyCR6+ZnampIGZmja784g67rGTqwn/8Fh/nnig4CDvBZ06qX582CqjMiGDoA7mnYIv2vtJgc1mREZp0DIgQ5LPPLpqzy3VhjxXml0o=
  app: pacific-escarpment-98371
